config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root 'devise/sessions#new'
  end

  get 'welcome2/index'
  get 'welcome/index'
  
  get 'patients/list'
  get 'patients/new'
  post 'patients/create'
  patch 'patients/update'
  get 'patients/list'
  get 'patients/show'
  get 'patients/edit'
  get 'patients/delete'
  get 'patients/update'
  
  resources :patients do
    member do
      get :add_doctor
      post :create_doctor
      get :show_doctors
      get :delete_doctors
    end
  end

  get 'doctors/list'
  get 'doctors/new'
  post 'doctors/create'
  patch 'doctors/update'
  get 'doctors/list'
  get 'doctors/show'
  get 'doctors/edit'
  get 'doctors/delete'
  get 'doctors/update'

  resources :doctors do
    member do
      get :add_patient
      post :create_patient
      get :show_patients
      get :delete_patients
    end
  end

  get 'medicines/list'
  get 'medicines/new'
  post 'medicines/create'
  patch 'medicines/update'
  get 'medicines/list'
  get 'medicines/show'
  get 'medicines/edit'
  get 'medicines/delete'
  get 'medicines/update'

  get 'appointments/list'
  get 'appointments/new'
  post 'appointments/create'
  patch 'appointments/update'
  get 'appointments/list'
  get 'appointments/show'
  get 'appointments/edit'
  get 'appointments/delete'
  get 'appointments/update'
  get 'appointments/show_patients'
  get 'appointments/show_medicines'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render file: "app/views/welcome/index", :formats => [:html]
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="section-parallax h-100 py-5" style="background-image: url('https://singularityhub.com/wp-content/uploads/2018/07/healthcare_shutterstock_277918613-1068x601.jpg');">
  <div class="container my-5 bg-light p-4">
    <div class="row mx-auto">
      <div class="col-md-12">
        <h1 class="mb-3"><b>MedClinic</b></h1>
        <p class="">The official platform of the MedClinic hospital, where you can see and edit your appointments, see doctors, medicines, and much more. Here, you can find anything, with one click.</p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="btn-group">
          <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><b>Patients</b></button>
          <div class="dropdown-menu">
            <%= link_to '<button class="dropdown-item"><b>See/Modify/Delete</b></button>'.html_safe, patients_list_path %>
            <div class="dropdown-divider"></div>
            <%= link_to '<button class="dropdown-item"><b>Add</b></button>'.html_safe, patients_new_path %>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="btn-group">
          <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><b>Doctors</b></button>
          <div class="dropdown-menu">
            <%= link_to '<button class="dropdown-item"><b>See/Modify/Delete</b></button>'.html_safe, doctors_list_path %>
            <div class="dropdown-divider"></div>
            <%= link_to '<button class="dropdown-item"><b>Add</b></button>'.html_safe, doctors_new_path %>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="btn-group">
          <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><b>Medicines</b></button>
          <div class="dropdown-menu">
            <%= link_to '<button class="dropdown-item"><b>See/Modify/Delete</b></button>'.html_safe, medicines_list_path %>
            <div class="dropdown-divider"></div>
            <%= link_to '<button class="dropdown-item"><b>Add</b></button>'.html_safe, medicines_new_path %>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="btn-group">
          <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><b>Appointments</b></button>
          <div class="dropdown-menu">
            <%= link_to '<button class="dropdown-item"><b>See/Modify/Delete</b></button>'.html_safe, appointments_list_path %>
            <div class="dropdown-divider"></div>
            <%= link_to '<button class="dropdown-item"><b>Add</b></button>'.html_safe, appointments_new_path %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-1">&nbsp; </h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5 section-aquamarine h-75" id="register">
    <div class="container">
      <div class="row">
        <div class="text-md-left text-center col-md-8">
          <h1 class="text-white">Write us!</h1>
          <p>You cand write us right here about any problem that you encounter or any issue. Also, we are open to suggestions about how we can improve the speed and format of this platform. Thank you!</p>
        </div>
        <div class="my-3 col-lg-4 col-md-4">
          <h3>Contact us</h3>
          <form action="index2.html">
            <fieldset class="form-group my-3">
              <input type="email" class="form-control" id="Input Email" placeholder="Email"> </fieldset>
              <fieldset class="form-group my-3">
                <input type="message" class="form-control" id="Input Message" placeholder="Message"> </fieldset>
                <%= link_to '<button class="btn btn-outline-dark text-light">Send</button>'.html_safe, welcome2_index_path %>
              </form>
            </div>
          </div>
        </div>
      </div>
      