config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root 'devise/sessions#new'
  end

  get 'welcome2/index'
  get 'welcome/index'
  
  get 'patients/list'
  get 'patients/new'
  post 'patients/create'
  patch 'patients/update'
  get 'patients/list'
  get 'patients/show'
  get 'patients/edit'
  get 'patients/delete'
  get 'patients/update'
  
  resources :patients do
    member do
      get :add_doctor
      post :create_doctor
      get :show_doctors
      get :delete_doctors
    end
  end

  get 'doctors/list'
  get 'doctors/new'
  post 'doctors/create'
  patch 'doctors/update'
  get 'doctors/list'
  get 'doctors/show'
  get 'doctors/edit'
  get 'doctors/delete'
  get 'doctors/update'

  resources :doctors do
    member do
      get :add_patient
      post :create_patient
      get :show_patients
      get :delete_patients
    end
  end

  get 'medicines/list'
  get 'medicines/new'
  post 'medicines/create'
  patch 'medicines/update'
  get 'medicines/list'
  get 'medicines/show'
  get 'medicines/edit'
  get 'medicines/delete'
  get 'medicines/update'

  get 'appointments/list'
  get 'appointments/new'
  post 'appointments/create'
  patch 'appointments/update'
  get 'appointments/list'
  get 'appointments/show'
  get 'appointments/edit'
  get 'appointments/delete'
  get 'appointments/update'
  get 'appointments/show_patients'
  get 'appointments/show_medicines'
end

app/models/appointment.rb
class Appointment < ApplicationRecord

  #Relationships
  belongs_to :patient
  belongs_to :medicine

  validates :medicine_dose, numericality: true
  validates :appointment_date, :patient_id, :medicine_id, presence: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :load_appointment, only: %i[show edit update delete]
  before_action :load_appointments, only: %i[list]
  before_action :load_patients, only: %i[new edit]
  before_action :load_medicines, only: %i[new edit]

  def list
    @appointments
  end

  def show
    @appointment
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
  
    if @appointment.save
      redirect_to :action => 'list'
   else
      @error = @appointment.errors
      render file: "app/views/error"
   end
  end

  def appointment_params
    params.require(:appointment).permit(:patient_id, :medicine_id, :appointment_date, :diagnostic, :medicine_dose)
  end

  def edit
    @appointment
  end

  def update
    if @appointment.update_attributes(appointment_params)
      redirect_to :action => 'show', :id => @appointment
    else
      @error = @appointment.errors
      render file: "app/views/error"
    end
  end

  def delete
    if current_user.admin
      @appointment.destroy
      redirect_to :action => 'list'
    else
      @error = "The current user is not an admin."
    end
  end

  private

  def load_appointment
    @appointment = Appointment.find(params[:id])
  end

  def load_appointments
    @appointments = Appointment.all.order(created_at: :desc)
  end

  def load_patients
    @patients = Patient.all.order(created_at: :desc)
  end

  def load_medicines
    @medicines = Medicine.all.order(created_at: :desc)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/edit.html.erb
<div class="section-parallax h-100 py-5 opaque-overlay" style="background-image: url('https://singularityhub.com/wp-content/uploads/2018/07/healthcare_shutterstock_277918613-1068x601.jpg');">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h5 class="display-5 text-left pl-5 text-white"></h5>
      </div>
    </div>
  </div>
  <div class="container-">
    <div class="row">
      <div class="col-md-12">
        <h1 class="display-1"></h1>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6"></div>
        <div class="col-md-6 text-center">
          <%= form_for @appointment, :url =>{action: :update, id: @appointment.id} do |f| %>
          <div class="col-md-12">
            <h3 class="display-5 text-left  text-center text-white">Edit Appointment info</h3>
          </div>
          <div class="col-md-12">
            <h5 class="display-5 text-left pl-5 text-white">&nbsp</h5>
          </div>
          <div class="form-group row"> <label for="appointment_patient_id" class="col-5 col-form-label text-white">Patient</label>
            <div class="col-3">
              <%= f.collection_select(:patient_id, @patients, :id, :full_name) %> 
            </div>
          </div>
          <h5 class="display-5"></h5>
          <div class="form-group row"> 
            <label for="appointment_medicine_id" class="col-5 col-form-label text-white">Medicine</label>
            <div class="col-3">
              <%= f.collection_select(:medicine_id, @medicines, :id, :name) %>
            </div>
          </div>
          <h5 class="display-5"></h5>
          <div class="form-group row"> 
            <label for="appointment_appointment_date" class="col-5 col-form-label text-white">Date</label>
            <div class="col-3">
              <%= f.date_field 'appointment_date' %> 
            </div>
          </div>
          <h5 class="display-5"></h5>
          <div class="form-group row"> 
            <label for="appointment_diagnostic" class="col-5 col-form-label text-white">Diagnosis</label>
            <div class="col-3">
              <%= f.text_field 'diagnostic' %> 
            </div>
          </div>
          <h5 class="display-5"></h5>
          <div class="form-group row"> 
            <label for="appointment_medicine_dose" class="col-5 col-form-label text-white">Medicine daily dose</label>
            <div class="col-3">
              <%= f.text_field 'medicine_dose' %>
            </div>
          </div>
          <div class="col-md-5">
            <h1>&nbsp</h1>
          </div>
          <button type="submit" class="btn btn-primary w-25">Update</button>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <h1 class="display-1 text-left pl-5 text-white">&nbsp</h1>
    </div>
  </div>
</div>

app/views/appointments/list.html.erb
<% if @appointments.blank? %>
<div class="section-parallax h-100 py-5 opaque-overlay" style="background-image: url('https://singularityhub.com/wp-content/uploads/2018/07/healthcare_shutterstock_277918613-1068x601.jpg');">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="display-5">&nbsp; </h2>
        <h2 class="text-white text-center">There are not any appointments currently in the system</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h1 class="display-5">&nbsp; </h1>
      </div>
    </div>
  </div>
</div>
<% else %>
<div class="section-parallax h-100 py-5 opaque-overlay" style="background-image: url('https://singularityhub.com/wp-content/uploads/2018/07/healthcare_shutterstock_277918613-1068x601.jpg');">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="display-5">&nbsp; </h2>
        <h2 class="text-white text-center">These are the appointments currently in your system</h2>
      </div>
    </div>
  </div>
  <div class="row">
    <h1 class="display-5">&nbsp; </h1>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="list-group text-left">
          <% @appointments.each do |appointment| %>
          <div class="row text-center">
            <div class="col-md-6 text-center">
              <%= link_to appointment.appointment_date, {action: :show, id: appointment.id}, class: "list-group-item list-group-item-action" -%> 
            </div>
            <div class="col-md-6 text-center">
              <b> <%= link_to 'Edit', {action: :edit, id: appointment.id} %></b>
              <% if current_user.admin%>
              <b> <%= link_to "Delete", {action: :delete, id: appointment.id},data: {confirm: "Are you sure?"}%></b>
              <%end%>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
    <div class="row">
      <h1 class="display-1">&nbsp; </h1>
    </div>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="section-parallax h-100 py-5 opaque-overlay" style="background-image: url('https://singularityhub.com/wp-content/uploads/2018/07/healthcare_shutterstock_277918613-1068x601.jpg');">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h5 class="display-5 text-left pl-5 text-white"></h5>
      </div>
    </div>
  </div>
  <div class="container-">
    <div class="row">
      <div class="col-md-12">
        <h1 class="display-1"></h1>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
        </div>
        <div class="col-md-6 text-center">
          <%=  form_for @appointment, as: :appointment, url: appointments_create_path(@appointment), method: :post do %>
          <div class="col-md-12">
            <h3 class="display-5 text-left  text-center text-white">Add a new Appointment</h3>
          </div>
          <div class="col-md-12">
            <h5 class="display-5 text-left pl-5 text-white">&nbsp</h5>
          </div>
          <div class="form-group row"> 
            <label for="appointment_patient_id" class="col-5 col-form-label text-white">Patient</label>
            <div class="col-3">
              <%= collection_select(:appointment, :patient_id, @patients, :id, :full_name) %>
            </div>
          </div>
          <h5 class="display-5"></h5>
          <div class="form-group row"> 
            <label for="appointment_medicine_id" class="col-5 col-form-label text-white">Medicine</label>
            <div class="col-3">
              <%= collection_select(:appointment, :medicine_id, @medicines, :id, :name) %>
            </div>
          </div>
          <h5 class="display-5"></h5>
          <div class="form-group row"> 
            <label for="appointment_appointment_date" class="col-5 col-form-label text-white">Date</label>
            <div class="col-3">
              <%= date_field 'appointment', 'appointment_date' %> 
            </div>
          </div>
          <h5 class="display-5"></h5>
          <div class="form-group row"> 
            <label for="appointment_diagnostic" class="col-5 col-form-label text-white">Diagnosis</label>
            <div class="col-3">
              <%= text_field 'appointment', 'diagnostic' %> 
            </div>
          </div>
          <h5 class="display-5"></h5>
          <div class="form-group row"> 
            <label for="appointment_medicine_dose" class="col-5 col-form-label text-white">Medicine daily dose</label>
            <div class="col-3">
              <%= text_field 'appointment', 'medicine_dose' %>
            </div>
          </div>
          <div class="col-md-5"><h1>&nbsp</h1>
          </div>
          <button type="submit" class="btn btn-primary w-25">Add</button>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <h1 class="display-1 text-left pl-5 text-white">&nbsp</h1>
    </div>
  </div>
</div>

app/views/appointments/show.html.erb
<div class="section-parallax h-100 py-5 opaque-overlay" style="background-image: url('https://singularityhub.com/wp-content/uploads/2018/07/healthcare_shutterstock_277918613-1068x601.jpg');">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="text-left text-white">Appointment #<%= @appointment.id %></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2 class="display-5">&nbsp</h2>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="list-group text-left">
          <a class="list-group-item list-group-item-action">Patient: <%= @appointment.patient.full_name %></a>
          <a class="list-group-item list-group-item-action">Medicine: <%= @appointment.medicine.name %></a>
          <a class="list-group-item list-group-item-action">Date: <%= @appointment.appointment_date %></a>
          <a class="list-group-item list-group-item-action">Diagnosis: <%= @appointment.diagnostic %></a>
          <a class="list-group-item list-group-item-action">Medicine daily dose: <%= @appointment.medicine_dose %></a>
        </div>
      </div>
      <div class="col-md-6"></div>
    </div>
    <div class="row">
      <div class="col-md-12">
       <h2 class="display-5">&nbsp</h2>   
     </div>
   </div>
   <div class="row">
    <div class="col-md-12 text-left ml-5">
      <%= link_to '<button class="btn btn-primary" href="#" >Back</button>'.html_safe, {action: :list} %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-left ml-5">
      <h2 class="display-5">&nbsp</h2>
    </div>
  </div>
</div>